on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  certora_run_submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Submit verification jobs to Certora Prover
        uses: Certora/certora-run-action@v2
        with:
          # Add your configurations as lines, each line is separated.
          # Specify additional options for each configuration by adding them after the configuration.
          configurations: |-
            certora/confs/ECDSATableCalculator.conf
            certora/confs/AVSRegistrarWithAllowlist.conf
            certora/confs/BN254TableCalculator.conf
            certora/confs/AVSRegistrarWithSocket.conf
            certora/confs/AVSRegistrar.conf
          solc-versions: 0.8.27
          job-name: "Verified Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
